# Setup

In [6]:
# Setup
import json
import os
import sys
from datetime import datetime, timedelta
import time
from dotenv import load_dotenv, set_key
import random
from pathlib import Path

# hashing for signing
import hashlib
import hmac

# requests
import requests

# data munging
import pandas as pd

# helper functions
from tiktok_api_helpers import *

## Settings

In [14]:
new_access_token = False
use_refresh_token = False

## Constants

In [8]:
base_url = "https://open-api.tiktokglobalshop.com"

In [9]:
load_dotenv()  # reads .env in the current directory into environment variables

app_key = os.environ.get("TIKTOK_APP_KEY")
app_secret = os.environ.get("TIKTOK_APP_SECRET")
auth_code = os.environ.get("TIKTOK_AUTH_CODE")
shop_cipher = os.environ.get("SHOP_CIPHER")

In [ ]:
load_dotenv()  # reads .env in the current directory into environment variables

app_key = os.environ.get("TIKTOK_APP_KEY")
app_secret = os.environ.get("TIKTOK_APP_SECRET")
access_token = os.environ.get("TIKTOK_ACCESS_TOKEN")
shop_cipher = os.environ.get("SHOP_CIPHER")

base_url = "https://open-api.tiktokglobalshop.com"
path = "/affiliate_seller/202508/marketplace_creators/search"

INPUT_CSV = "all_creators_handleonly.csv"
CONSOLIDATED_CSV = "creators_found.csv"
MANIFEST_CSV = "creators_manifest.csv"
DELAY_BETWEEN_CALLS = 1.0  # seconds, to be gentle on the rate limit
RATE_LIMIT_CODE = 36009002

## Load data

In [48]:
list_all_creators = pd.read_csv("all_creators_handleonly.csv")['Handle'].tolist()

## Helper functions

# API Setup

## 1. Get Access Token

In [15]:
if (new_access_token | use_refresh_token):

    # get new acces_token
    token_url = "https://auth.tiktok-shops.com/api/v2/token/get"

    if use_refresh_token:
        auth_code = os.environ.get("TIKTOK_REFRESH_TOKEN")
        
    params = {
        "app_key": app_key,
        "app_secret": app_secret,
        "auth_code": auth_code,
        "grant_type": "authorized_code",
    }
    
    response = requests.get(token_url, params=params, timeout=15)
    data = response.json()['data']
    access_token = data['access_token']
    print(data)

    # save tokens in .env file
    set_key(".env", "TIKTOK_ACCESS_TOKEN", data['access_token'])
    set_key(".env", "TIKTOK_REFRESH_TOKEN", data['refresh_token'])

else:
    access_token = os.environ.get("TIKTOK_ACCESS_TOKEN")
    refresh_token = os.environ.get("TIKTOK_REFRESH_TOKEN")

## 2. Get Shop Cipher

(True, 'SHOP_CIPHER', 'ROW_N6cpKQAAAADl57_xyhcxuGLS8aCEeYMb')

# Step 1: Get Creator Open IDs

In [ ]:
list_all_creators = pd.read_csv(INPUT_CSV)["Handle"].tolist()

# Load or initialize the manifest (tracks which handles are already found)
if Path(MANIFEST_CSV).exists():
    manifest = pd.read_csv(MANIFEST_CSV)
else:
    manifest = pd.DataFrame({"handle": list_all_creators, "found": False})

# Load or initialize consolidated creator data pulled so far
if Path(CONSOLIDATED_CSV).exists():
    df_creators = pd.read_csv(CONSOLIDATED_CSV)
else:
    df_creators = pd.DataFrame()

handles_to_find = manifest.loc[~manifest["found"], "handle"].tolist()
print(f"{len(handles_to_find)} handles left to find out of {len(manifest)} total.\n")

# Phase 1: chunk_size=5, single pass through everything not yet found
still_not_found, df_creators = run_pass(handles_to_find, chunk_size=5, df_creators=df_creators)

found_usernames = set(df_creators["username"].str.lower())
manifest["found"] = manifest["handle"].str.lstrip("@").str.lower().isin(found_usernames)
manifest.to_csv(MANIFEST_CSV, index=False)
print(f"\nPhase 1 done. {len(still_not_found)} handles still not found.\n")

# Phase 2: chunk_size=1, only for leftovers from phase 1
if still_not_found:
    _, df_creators = run_pass(still_not_found, chunk_size=1, df_creators=df_creators)

    found_usernames = set(df_creators["username"].str.lower())
    manifest["found"] = manifest["handle"].str.lstrip("@").str.lower().isin(found_usernames)
    manifest.to_csv(MANIFEST_CSV, index=False)

print(f"\nDone. {int(manifest['found'].sum())} / {len(manifest)} handles found.")
print(f"Consolidated data: {Path(CONSOLIDATED_CSV).resolve()}")
print(f"Manifest: {Path(MANIFEST_CSV).resolve()}")

In [73]:
keyword_list = list_all_creators[5:10]

In [74]:
keyword = '@'+"|@".join(keyword_list)
print(keyword)

@iphonatics|@moto.math|@annalmoite|@zy.mendoza.gerond|@mikebalolong

In [86]:
path = "/affiliate_seller/202508/marketplace_creators/search"

# setup parameters
params = {
    "app_key": app_key,
    "timestamp": int(time.time()),
    "shop_cipher": shop_cipher,
    "page_size":20,
}

# setup search keywords
body_dict = {
    "keyword": keyword,
    'search_key': search_key
}
body = json.dumps(body_dict)
signed_params = build_signed_params(path, params, app_secret, body)

# send request
response = requests.post(
    f"{base_url}{path}",
    params=signed_params,
    data=body,
    headers={"x-tts-access-token": access_token, "content-type": "application/json"},
    timeout=15,
)
print(f"Status: {response.status_code}")

Status: 200

In [87]:
search_key = response.json()['data']['search_key']

In [81]:
keyword = '@iphonatics|@annalmoite|@zy.mendoza.gerond'

In [88]:
pd.DataFrame(response.json()['data']['creators'])

,avatar,avg_ec_live_uv,avg_ec_video_view_count,category_ids,creator_open_id,follower_count,gmv,gmv_range,live_gmv,nickname,selection_region,top_follower_demographics,username,video_gmv
0,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,2874,"[824328, 601152, 603014]",7uArVgAAAACOV4AEeERJl-yievH_HBssyCoWST9L0ZrCkD...,194943,"{'amount': '267947.693812', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...","{'amount': '2.658677', 'currency': 'USD'}",Miss Ann ✿,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",annalmoite,"{'amount': '267737.248135', 'currency': 'USD'}"
1,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,2157,"[601739, 600001]",yGLEYQAAAACOV4AEeERJl-yievH_HBsseWu9pSsIf9zLL8...,611913,"{'amount': '211924.621037', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...","{'amount': '6.83353', 'currency': 'USD'}",IPHONATICS,PH,"{'age_ranges': ['AGE_RANGE_18_24', 'AGE_RANGE_...",iphonatics,"{'amount': '208758.776693', 'currency': 'USD'}"
2,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601739, 604453, 600154]",S7jHnQAAAACOV4AEeERJl-yievH_HBsspmDYP-pIAVrUlv...,31731,NaN,{'formatted_range': '₱10K+'},NaN,Almira Carriaga,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",almiracarriaga,NaN
3,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 600001]",9Ovn_wAAAACOV4AEeERJl-yievH_HBssS7BIL5paEZ6qYL...,531,NaN,{'formatted_range': '₱10K+'},NaN,Maria,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",user5844826884387,NaN
4,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 600001]",3MxrrwAAAACOV4AEeERJl-yievH_HBssPMIZu50b8vQOzm...,13,"{'amount': '5825500.518508', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...",NaN,iflyad03,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",iflyad03,NaN
5,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 605196]",T51HRwAAAACOV4AEeERJl-yievH_HBsscpim0sGFIiscz9...,1,NaN,{'formatted_range': '₱10K+'},NaN,ShopAtHomePH,PH,"{'age_ranges': ['AGE_RANGE_35_44'], 'major_gen...",shopathomeph,NaN
6,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601739, 605196, 601450]",Bk01NQAAAACOV4AEeERJl-yievH_HBssjYBT2NCiw6gm5a...,785,"{'amount': '28265.648061', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...",NaN,Nicolas Pagquil,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",nicolas.pagquil,NaN
7,{'url': 'https://p16-common-sign.tiktokcdn.com...,102597,0,"[601739, 601755]",jSATJgAAAACOV4AEeERJl-yievH_HBssugnh2geIdZYbIX...,114461,NaN,{'formatted_range': '₱10K+'},NaN,Hari ng Chamba,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",haringchamba,NaN
8,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,281,"[601739, 604968, 605196]",4WFi3gAAAACOV4AEeERJl-yievH_HBss5966XF9PQoqdpS...,20709,"{'amount': '22730.431964', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...",NaN,Egi finds,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",egii_tv_06,"{'amount': '22730.431964', 'currency': 'USD'}"
9,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 600001]",yJHLEAAAAACOV4AEeERJl-yievH_HBss0zwVS1hGagjS2u...,0,NaN,{'formatted_range': '₱10K+'},NaN,Manh Vinh,PH,"{'age_ranges': [], 'major_gender': {'gender': ...",manh.vinh82,NaN
10,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,1087,"[601739, 600942]",-uHJVwAAAACOV4AEeERJl-yievH_HBssG-ElhJbBUq3CB3...,64661,"{'amount': '473522.230622', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...",NaN,𝙊𝙣𝙞𝙤𝙣ᥫ᭡.,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",b.rencee,"{'amount': '473335.666657', 'currency': 'USD'}"
11,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,237,"[601739, 601450]",XoTXawAAAACOV4AEeERJl-yievH_HBssONvLAt04stNsY9...,38792,"{'amount': '45038.921091', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...",NaN,Kalye Guapo,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",kalyeguapo,"{'amount': '44979.911741', 'currency': 'USD'}"
12,{'url': 'https://p16-common-sign.tiktokcdn.com...,17852,0,[601739],LfIZEgAAAACOV4AEeERJl-yievH_HBsscZ8ZHmnps_JQgs...,1609,NaN,{'formatted_range': '₱10K+'},NaN,vthykhanh339,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",vthykhanh339,NaN
13,{'url': 'https://p16-common-sign.tiktokcdn.com...,7678,0,[601739],cpkUwgAAAACOV4AEeERJl-yievH_HBssT5zIbCZM6VeePj...,2142,NaN,{'formatted_range': '₱10K+'},NaN,TambokTreasures,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",cellphone.shop596,NaN
14,{'url': 'https://p16-common-sign.tiktokcdn.com...,4524,0,"[601739, 604206]",MJpuawAAAACOV4AEeERJl-yievH_HBss-BKfIzRzB0IznW...,938,NaN,{'formatted_range': '₱10K+'},NaN,RizalRattan,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",gadgetdrop83,NaN
15,{'url': 'https://p16-common-sign.tiktokcdn.com...,9278,378,"[601739, 604206]",A411nwAAAACOV4AEeERJl-yievH_HBss_S4oMLwmJVXppi...,81006,"{'amount': '40578.691485', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...","{'amount': '35562.330301', 'currency': 'USD'}",Amy David,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",amydavid22,"{'amount': '4716.721096', 'currency': 'USD'}"
16,{'url': 'https://p16-common-sign.tiktokcdn.com...,17230,0,[601739],xeVgAAAAAACOV4AEeERJl-yievH_HBsswKG2Z6Z7eT5ND_...,2208,NaN,{'formatted_range': '₱10K+'},NaN,GameSexy PH,PH,"{'age_ranges': ['AGE_RANGE_55_AND_ABOVE', 'AGE...",gamesexyph,NaN
17,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,371,"[601739, 601352, 601450]",HLzZ_AAAAACOV4AEeERJl-yievH_HBssy3xbxY8iZgLcv2...,29782,"{'amount': '88525.422884', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...",NaN,Anne28,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",05garutay,"{'amount': '88508.090678', 'currency': 'USD'}"
18,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 600001]",0RFWIwAAAACOV4AEeERJl-yievH_HBsstWx_jsTo2lvOIs...,4,NaN,{'formatted_range': '₱10K+'},NaN,involveasiaph02,PH,"{'age_ranges': ['AGE_RANGE_55_AND_ABOVE', 'AGE...",involveasiaph02,NaN
19,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 605196]",wvWCCAAAAACOV4AEeERJl-yievH_HBssoGCY5fVpWxx9iO...,8,NaN,{'formatted_range': '₱10K+'},NaN,involveasiaph01,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",involveasiaph01,NaN

In [80]:
pd.DataFrame(response.json()['data']['creators'])

,avatar,avg_ec_live_uv,avg_ec_video_view_count,category_ids,creator_open_id,follower_count,gmv_range,nickname,selection_region,top_follower_demographics,username,gmv,live_gmv,video_gmv
0,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,1230,"[601450, 601739, 601755]",dbY-eAAAAACOV4AEeERJl-yievH_HBss139WeLpZGcLm-7...,795812,{'formatted_range': '₱10K+'},Mike Balolong,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",mikebalolong,NaN,NaN,NaN
1,{'url': 'https://p16-common-sign.tiktokcdn.com...,2093,4506,"[605196, 603014, 604453]",WQB7JgAAAACOV4AEeERJl-yievH_HBssNH0R3AlIg46elZ...,53365,"{'currency': 'USD', 'formatted_range': '₱10K+'...",Moto Math,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",moto.math,"{'amount': '243375.06568', 'currency': 'USD'}","{'amount': '485.304058', 'currency': 'USD'}","{'amount': '242618.434792', 'currency': 'USD'}"
2,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601739, 604453, 600154]",S7jHnQAAAACOV4AEeERJl-yievH_HBsspmDYP-pIAVrUlv...,31731,{'formatted_range': '₱10K+'},Almira Carriaga,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",almiracarriaga,NaN,NaN,NaN
3,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 600001]",9Ovn_wAAAACOV4AEeERJl-yievH_HBssS7BIL5paEZ6qYL...,531,{'formatted_range': '₱10K+'},Maria,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",user5844826884387,NaN,NaN,NaN
4,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 600001]",3MxrrwAAAACOV4AEeERJl-yievH_HBssPMIZu50b8vQOzm...,13,"{'currency': 'USD', 'formatted_range': '₱10K+'...",iflyad03,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",iflyad03,"{'amount': '5825500.518508', 'currency': 'USD'}",NaN,NaN
5,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 605196]",T51HRwAAAACOV4AEeERJl-yievH_HBsscpim0sGFIiscz9...,1,{'formatted_range': '₱10K+'},ShopAtHomePH,PH,"{'age_ranges': ['AGE_RANGE_35_44'], 'major_gen...",shopathomeph,NaN,NaN,NaN
6,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601739, 605196, 601450]",Bk01NQAAAACOV4AEeERJl-yievH_HBssjYBT2NCiw6gm5a...,785,"{'currency': 'USD', 'formatted_range': '₱10K+'...",Nicolas Pagquil,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",nicolas.pagquil,"{'amount': '28265.648061', 'currency': 'USD'}",NaN,NaN
7,{'url': 'https://p16-common-sign.tiktokcdn.com...,102597,0,"[601739, 601755]",jSATJgAAAACOV4AEeERJl-yievH_HBssugnh2geIdZYbIX...,114461,{'formatted_range': '₱10K+'},Hari ng Chamba,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",haringchamba,NaN,NaN,NaN
8,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,281,"[601739, 604968, 605196]",4WFi3gAAAACOV4AEeERJl-yievH_HBss5966XF9PQoqdpS...,20709,"{'currency': 'USD', 'formatted_range': '₱10K+'...",Egi finds,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",egii_tv_06,"{'amount': '22730.431964', 'currency': 'USD'}",NaN,"{'amount': '22730.431964', 'currency': 'USD'}"
9,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 600001]",yJHLEAAAAACOV4AEeERJl-yievH_HBss0zwVS1hGagjS2u...,0,{'formatted_range': '₱10K+'},Manh Vinh,PH,"{'age_ranges': [], 'major_gender': {'gender': ...",manh.vinh82,NaN,NaN,NaN
10,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,1087,"[601739, 600942]",-uHJVwAAAACOV4AEeERJl-yievH_HBssG-ElhJbBUq3CB3...,64661,"{'currency': 'USD', 'formatted_range': '₱10K+'...",𝙊𝙣𝙞𝙤𝙣ᥫ᭡.,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",b.rencee,"{'amount': '473522.230622', 'currency': 'USD'}",NaN,"{'amount': '473335.666657', 'currency': 'USD'}"
11,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,237,"[601739, 601450]",XoTXawAAAACOV4AEeERJl-yievH_HBssONvLAt04stNsY9...,38792,"{'currency': 'USD', 'formatted_range': '₱10K+'...",Kalye Guapo,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",kalyeguapo,"{'amount': '45038.921091', 'currency': 'USD'}",NaN,"{'amount': '44979.911741', 'currency': 'USD'}"
12,{'url': 'https://p16-common-sign.tiktokcdn.com...,17852,0,[601739],LfIZEgAAAACOV4AEeERJl-yievH_HBsscZ8ZHmnps_JQgs...,1609,{'formatted_range': '₱10K+'},vthykhanh339,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",vthykhanh339,NaN,NaN,NaN
13,{'url': 'https://p16-common-sign.tiktokcdn.com...,7678,0,[601739],cpkUwgAAAACOV4AEeERJl-yievH_HBssT5zIbCZM6VeePj...,2142,{'formatted_range': '₱10K+'},TambokTreasures,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",cellphone.shop596,NaN,NaN,NaN
14,{'url': 'https://p16-common-sign.tiktokcdn.com...,4524,0,"[601739, 604206]",MJpuawAAAACOV4AEeERJl-yievH_HBss-BKfIzRzB0IznW...,938,{'formatted_range': '₱10K+'},RizalRattan,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",gadgetdrop83,NaN,NaN,NaN
15,{'url': 'https://p16-common-sign.tiktokcdn.com...,9278,378,"[601739, 604206]",A411nwAAAACOV4AEeERJl-yievH_HBss_S4oMLwmJVXppi...,81006,"{'currency': 'USD', 'formatted_range': '₱10K+'...",Amy David,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",amydavid22,"{'amount': '40578.691485', 'currency': 'USD'}","{'amount': '35562.330301', 'currency': 'USD'}","{'amount': '4716.721096', 'currency': 'USD'}"
16,{'url': 'https://p16-common-sign.tiktokcdn.com...,17230,0,[601739],xeVgAAAAAACOV4AEeERJl-yievH_HBsswKG2Z6Z7eT5ND_...,2208,{'formatted_range': '₱10K+'},GameSexy PH,PH,"{'age_ranges': ['AGE_RANGE_55_AND_ABOVE', 'AGE...",gamesexyph,NaN,NaN,NaN
17,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,371,"[601739, 601352, 601450]",HLzZ_AAAAACOV4AEeERJl-yievH_HBssy3xbxY8iZgLcv2...,29782,"{'currency': 'USD', 'formatted_range': '₱10K+'...",Anne28,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",05garutay,"{'amount': '88525.422884', 'currency': 'USD'}",NaN,"{'amount': '88508.090678', 'currency': 'USD'}"
18,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 600001]",0RFWIwAAAACOV4AEeERJl-yievH_HBsstWx_jsTo2lvOIs...,4,{'formatted_range': '₱10K+'},involveasiaph02,PH,"{'age_ranges': ['AGE_RANGE_55_AND_ABOVE', 'AGE...",involveasiaph02,NaN,NaN,NaN
19,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 605196]",wvWCCAAAAACOV4AEeERJl-yievH_HBssoGCY5fVpWxx9iO...,8,{'formatted_range': '₱10K+'},involveasiaph01,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",involveasiaph01,NaN,NaN,NaN

In [69]:
pd.DataFrame(response.json()['data']['creators'])

,avatar,avg_ec_live_uv,avg_ec_video_view_count,category_ids,creator_open_id,follower_count,gmv_range,nickname,selection_region,top_follower_demographics,username,gmv,video_gmv
0,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601352, 601152]",I2IWFwAAAACOV4AEeERJl-yievH_HBssOVaC2_feBRCR7I...,894,{'formatted_range': '₱100-₱1K'},Jpongs_,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",jpolimar2nd,NaN,NaN
1,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601152, 600942, 603014]",FJXiWgAAAACOV4AEeERJl-yievH_HBss6kZoZmHqG7TSuA...,1922,{'formatted_range': '₱0-₱100'},jomaryeedump,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",jomaryeedump_2000,NaN,NaN
2,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,3921,"[600001, 700437, 601739]",0Ktl2wAAAACOV4AEeERJl-yievH_HBss98ZZMcc5NxLGOJ...,127228,"{'currency': 'USD', 'formatted_range': '₱10K+'...",david sy,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",david.sy25,"{'amount': '198894.218417', 'currency': 'USD'}","{'amount': '198810.840923', 'currency': 'USD'}"
3,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[605196, 603014, 604579]",ekTRtQAAAACOV4AEeERJl-yievH_HBssjAnMhoUO18D0YG...,7043,{'formatted_range': '₱0-₱100'},jomaryeedump,PH,"{'age_ranges': ['AGE_RANGE_18_24'], 'major_gen...",jomaryeedump52,NaN,NaN
4,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,2304,"[601352, 603014, 604453]",Y5EkgwAAAACOV4AEeERJl-yievH_HBssTrKMtvBlwwqFdF...,88875,{'formatted_range': '₱10K+'},Jp Olimar🇵🇭,PH,"{'age_ranges': ['AGE_RANGE_18_24'], 'major_gen...",jpongs_,NaN,NaN
5,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,1431,"[600942, 801928, 602284]",OjX16gAAAACOV4AEeERJl-yievH_HBssLMogjZiSaMeXxo...,27361,{'formatted_range': '₱10K+'},Karen Anonas,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",karenanonas,NaN,NaN

In [63]:
pd.DataFrame(response.json()['data']['creators'])

,avatar,avg_ec_live_uv,avg_ec_video_view_count,category_ids,creator_open_id,follower_count,gmv_range,nickname,selection_region,top_follower_demographics,username,gmv,video_gmv,live_gmv
0,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601352, 601152]",I2IWFwAAAACOV4AEeERJl-yievH_HBssOVaC2_feBRCR7I...,894,{'formatted_range': '₱100-₱1K'},Jpongs_,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",jpolimar2nd,NaN,NaN,NaN
1,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 700645, 600942]",4-8EuQAAAACOV4AEeERJl-yievH_HBssVSbe7_5LcPqJXc...,2842,{'formatted_range': '₱100-₱1K'},Dump ni jomar yee,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",jomaryeedump_5,NaN,NaN,NaN
2,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601152, 600942, 603014]",FJXiWgAAAACOV4AEeERJl-yievH_HBss6kZoZmHqG7TSuA...,1922,{'formatted_range': '₱0-₱100'},jomaryeedump,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",jomaryeedump_2000,NaN,NaN,NaN
3,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[824584, 601152, 601450]",L7PcYwAAAACOV4AEeERJl-yievH_HBsshmh4OB3xdmSeP7...,1004,{'formatted_range': '₱0-₱100'},yuni okayde😊,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",jomaryeedumpz,NaN,NaN,NaN
4,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[824584, 600001, 600024]",giMQhgAAAACOV4AEeERJl-yievH_HBssdsfXKMGxp82a0j...,169,{'formatted_range': '₱0-₱100'},WenceslaoShop,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",jomaryeedump8,NaN,NaN,NaN
5,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,3921,"[600001, 700437, 601739]",0Ktl2wAAAACOV4AEeERJl-yievH_HBss98ZZMcc5NxLGOJ...,127228,"{'currency': 'USD', 'formatted_range': '₱10K+'...",david sy,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",david.sy25,"{'amount': '198894.218417', 'currency': 'USD'}","{'amount': '198810.840923', 'currency': 'USD'}",NaN
6,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[605196, 603014, 604579]",ekTRtQAAAACOV4AEeERJl-yievH_HBssjAnMhoUO18D0YG...,7043,{'formatted_range': '₱0-₱100'},jomaryeedump,PH,"{'age_ranges': ['AGE_RANGE_18_24'], 'major_gen...",jomaryeedump52,NaN,NaN,NaN
7,{'url': 'https://p19-common-sign.tiktokcdn.com...,0,1940,"[601352, 824328, 601152]",OlDpxwAAAACOV4AEeERJl-yievH_HBssyJrMiLFJf1B0bD...,26566,"{'currency': 'USD', 'formatted_range': '₱10K+'...",Fernando's Finds,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",majuuuuuuri,"{'amount': '105103.947971', 'currency': 'USD'}","{'amount': '103030.857739', 'currency': 'USD'}",NaN
8,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,43533,"[601450, 601152, 600001]",6vRP6QAAAACOV4AEeERJl-yievH_HBssm6EICBQi-rrSkp...,1566047,"{'currency': 'USD', 'formatted_range': '₱10K+'...",Queen Pitik QP,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",zy.mendoza.gerond,"{'amount': '190698.792037', 'currency': 'USD'}","{'amount': '187435.971618', 'currency': 'USD'}","{'amount': '2.412918', 'currency': 'USD'}"
9,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,2304,"[601352, 603014, 604453]",Y5EkgwAAAACOV4AEeERJl-yievH_HBssTrKMtvBlwwqFdF...,88875,{'formatted_range': '₱10K+'},Jp Olimar🇵🇭,PH,"{'age_ranges': ['AGE_RANGE_18_24'], 'major_gen...",jpongs_,NaN,NaN,NaN
10,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,15629,"[600001, 601739, 601352]",Ty9_YgAAAACOV4AEeERJl-yievH_HBssLu4i19vwLW98se...,2415662,{'formatted_range': '₱10K+'},Dump ni Jomar Yee,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",jomaryeedump_,NaN,NaN,NaN
11,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,1431,"[600942, 801928, 602284]",OjX16gAAAACOV4AEeERJl-yievH_HBssLMogjZiSaMeXxo...,27361,{'formatted_range': '₱10K+'},Karen Anonas,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",karenanonas,NaN,NaN,NaN

In [39]:
pd.DataFrame(response.json()['data']['creators'])

,avatar,avg_ec_live_uv,avg_ec_video_view_count,category_ids,creator_open_id,follower_count,gmv_range,nickname,selection_region,top_follower_demographics,username,gmv,video_gmv
0,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601352, 601152]",I2IWFwAAAACOV4AEeERJl-yievH_HBssOVaC2_feBRCR7I...,894,{'formatted_range': '₱100-₱1K'},Jpongs_,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",jpolimar2nd,NaN,NaN
1,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 700645, 600942]",4-8EuQAAAACOV4AEeERJl-yievH_HBssVSbe7_5LcPqJXc...,2842,{'formatted_range': '₱100-₱1K'},Dump ni jomar yee,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",jomaryeedump_5,NaN,NaN
2,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601152, 600942, 603014]",FJXiWgAAAACOV4AEeERJl-yievH_HBss6kZoZmHqG7TSuA...,1922,{'formatted_range': '₱0-₱100'},jomaryeedump,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",jomaryeedump_2000,NaN,NaN
3,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[824584, 601152, 601450]",L7PcYwAAAACOV4AEeERJl-yievH_HBsshmh4OB3xdmSeP7...,1004,{'formatted_range': '₱0-₱100'},yuni okayde😊,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",jomaryeedumpz,NaN,NaN
4,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[824584, 600001, 600024]",giMQhgAAAACOV4AEeERJl-yievH_HBssdsfXKMGxp82a0j...,169,{'formatted_range': '₱0-₱100'},WenceslaoShop,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",jomaryeedump8,NaN,NaN
5,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601755, 700645, 601739]",XTl2zwAAAACOV4AEeERJl-yievH_HBssRnaxqwIqDw63zr...,7,{'formatted_range': '₱0-₱100'},JOMARYEEDUMP,PH,"{'age_ranges': ['AGE_RANGE_18_24'], 'major_gen...",_lunaaserene,NaN,NaN
6,{'url': 'https://p19-common-sign.tiktokcdn.com...,0,3921,"[600001, 700437, 601739]",0Ktl2wAAAACOV4AEeERJl-yievH_HBss98ZZMcc5NxLGOJ...,127228,"{'currency': 'USD', 'formatted_range': '₱10K+'...",david sy,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",david.sy25,"{'amount': '198894.218417', 'currency': 'USD'}","{'amount': '198810.840923', 'currency': 'USD'}"
7,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[605196, 603014, 604579]",ekTRtQAAAACOV4AEeERJl-yievH_HBssjAnMhoUO18D0YG...,7043,{'formatted_range': '₱0-₱100'},jomaryeedump,PH,"{'age_ranges': ['AGE_RANGE_18_24'], 'major_gen...",jomaryeedump52,NaN,NaN
8,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,1940,"[601352, 824328, 601152]",OlDpxwAAAACOV4AEeERJl-yievH_HBssyJrMiLFJf1B0bD...,26566,"{'currency': 'USD', 'formatted_range': '₱10K+'...",Fernando's Finds,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",majuuuuuuri,"{'amount': '105103.947971', 'currency': 'USD'}","{'amount': '103030.857739', 'currency': 'USD'}"
9,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,2304,"[601352, 603014, 604453]",Y5EkgwAAAACOV4AEeERJl-yievH_HBssTrKMtvBlwwqFdF...,88875,{'formatted_range': '₱10K+'},Jp Olimar🇵🇭,PH,"{'age_ranges': ['AGE_RANGE_18_24'], 'major_gen...",jpongs_,NaN,NaN
10,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,15629,"[600001, 601739, 601352]",Ty9_YgAAAACOV4AEeERJl-yievH_HBssLu4i19vwLW98se...,2415662,{'formatted_range': '₱10K+'},Dump ni Jomar Yee,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",jomaryeedump_,NaN,NaN
11,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,1431,"[600942, 801928, 602284]",OjX16gAAAACOV4AEeERJl-yievH_HBssLMogjZiSaMeXxo...,27361,{'formatted_range': '₱10K+'},Karen Anonas,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",karenanonas,NaN,NaN

In [28]:
response.json()

{'code': 0,
 'data': {'creators': [],
  'next_page_token': '',
  'search_key': '3sf9V5goXkn1VA8nI9vFWisff4VZFPeFRkX2LsNEFho='},
 'message': 'Success',
 'request_id': '2026071311062493A16B16BDBC1D9DE682'}

In [113]:
pd.DataFrame(response.json()['data']['creators'])

,avatar,avg_ec_live_uv,avg_ec_video_view_count,category_ids,creator_open_id,follower_count,gmv_range,nickname,selection_region,top_follower_demographics,username,gmv,live_gmv,video_gmv
0,{'url': 'https://p19-common-sign.tiktokcdn.com...,0,0,"[601352, 601152]",I2IWFwAAAACOV4AEeERJl-yievH_HBssOVaC2_feBRCR7I...,895,{'formatted_range': '₱100-₱1K'},Jpongs_,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",jpolimar2nd,NaN,NaN,NaN
1,{'url': 'https://p19-common-sign.tiktokcdn.com...,0,0,"[601450, 801928, 600154]",4-8EuQAAAACOV4AEeERJl-yievH_HBssVSbe7_5LcPqJXc...,2843,{'formatted_range': '₱100-₱1K'},Dump ni jomar yee,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",jomaryeedump_5,NaN,NaN,NaN
2,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[700645, 601739, 602284]",FJXiWgAAAACOV4AEeERJl-yievH_HBss6kZoZmHqG7TSuA...,1923,{'formatted_range': '₱0-₱100'},jomaryeedump,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",jomaryeedump_2000,NaN,NaN,NaN
3,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[602118, 824584, 601739]",L7PcYwAAAACOV4AEeERJl-yievH_HBsshmh4OB3xdmSeP7...,1004,{'formatted_range': '₱0-₱100'},yuni okayde😊,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",jomaryeedumpz,NaN,NaN,NaN
4,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601739, 601755, 700645]",XTl2zwAAAACOV4AEeERJl-yievH_HBssRnaxqwIqDw63zr...,7,{'formatted_range': '₱0-₱100'},JOMARYEEDUMP,PH,"{'age_ranges': ['AGE_RANGE_18_24'], 'major_gen...",_lunaaserene,NaN,NaN,NaN
5,{'url': 'https://p16-common-sign.tiktokcdn.com...,1541,2090,"[601450, 700437, 602118]",tO3PiwAAAACOV4AEeERJl-yievH_HBssheFI3rImSFcsoj...,30423,{'formatted_range': '₱10K+'},Ms.Arianne,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",cutyywee,NaN,NaN,NaN
6,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601352, 604968, 605248]",ekTRtQAAAACOV4AEeERJl-yievH_HBssjAnMhoUO18D0YG...,7046,{'formatted_range': '₱0-₱100'},jomaryeedump,PH,"{'age_ranges': ['AGE_RANGE_18_24'], 'major_gen...",jomaryeedump52,NaN,NaN,NaN
7,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,40710,"[601450, 601152, 600001]",6vRP6QAAAACOV4AEeERJl-yievH_HBssm6EICBQi-rrSkp...,1562234,"{'currency': 'USD', 'formatted_range': '₱10K+'...",Queen Pitik QP,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",zy.mendoza.gerond,"{'amount': '188717.341955', 'currency': 'USD'}","{'amount': '2.412918', 'currency': 'USD'}","{'amount': '185559.124598', 'currency': 'USD'}"
8,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,2243,"[601352, 603014, 604453]",Y5EkgwAAAACOV4AEeERJl-yievH_HBssTrKMtvBlwwqFdF...,88806,{'formatted_range': '₱10K+'},Jp Olimar🇵🇭,PH,"{'age_ranges': ['AGE_RANGE_18_24'], 'major_gen...",jpongs_,NaN,NaN,NaN

In [106]:
pd.DataFrame(response.json()['data']['creators'])

,avatar,avg_ec_live_uv,avg_ec_video_view_count,category_ids,creator_open_id,follower_count,gmv_range,nickname,selection_region,top_follower_demographics,username,gmv,video_gmv,live_gmv
0,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601352, 601152]",I2IWFwAAAACOV4AEeERJl-yievH_HBssOVaC2_feBRCR7I...,895,{'formatted_range': '₱100-₱1K'},Jpongs_,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",jpolimar2nd,NaN,NaN,NaN
1,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,2243,"[601352, 603014, 604453]",Y5EkgwAAAACOV4AEeERJl-yievH_HBssTrKMtvBlwwqFdF...,88806,{'formatted_range': '₱10K+'},Jp Olimar🇵🇭,PH,"{'age_ranges': ['AGE_RANGE_18_24'], 'major_gen...",jpongs_,NaN,NaN,NaN
2,{'url': 'https://p19-common-sign.tiktokcdn.com...,0,1385,"[600942, 801928, 602284]",OjX16gAAAACOV4AEeERJl-yievH_HBssLMogjZiSaMeXxo...,27338,{'formatted_range': '₱10K+'},Karen Anonas,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",karenanonas,NaN,NaN,NaN
3,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601739, 600001, 604453]",S7jHnQAAAACOV4AEeERJl-yievH_HBsspmDYP-pIAVrUlv...,31734,{'formatted_range': '₱10K+'},Almira Carriaga,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",almiracarriaga,NaN,NaN,NaN
4,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 600001]",9Ovn_wAAAACOV4AEeERJl-yievH_HBssS7BIL5paEZ6qYL...,531,{'formatted_range': '₱10K+'},Maria,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",user5844826884387,NaN,NaN,NaN
5,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 600001]",3MxrrwAAAACOV4AEeERJl-yievH_HBssPMIZu50b8vQOzm...,12,"{'currency': 'USD', 'formatted_range': '₱10K+'...",iflyad03,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",iflyad03,"{'amount': '5637882.296699', 'currency': 'USD'}",NaN,NaN
6,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 605196]",T51HRwAAAACOV4AEeERJl-yievH_HBsscpim0sGFIiscz9...,1,{'formatted_range': '₱10K+'},ShopAtHomePH,PH,"{'age_ranges': ['AGE_RANGE_35_44'], 'major_gen...",shopathomeph,NaN,NaN,NaN
7,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601739, 605196, 601450]",Bk01NQAAAACOV4AEeERJl-yievH_HBssjYBT2NCiw6gm5a...,787,"{'currency': 'USD', 'formatted_range': '₱10K+'...",Nicolas Pagquil,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",nicolas.pagquil,"{'amount': '28293.612369', 'currency': 'USD'}",NaN,NaN
8,{'url': 'https://p16-common-sign.tiktokcdn.com...,102597,0,"[601739, 601755]",jSATJgAAAACOV4AEeERJl-yievH_HBssugnh2geIdZYbIX...,114602,{'formatted_range': '₱10K+'},Hari ng Chamba,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",haringchamba,NaN,NaN,NaN
9,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,263,"[601739, 604968, 605196]",4WFi3gAAAACOV4AEeERJl-yievH_HBss5966XF9PQoqdpS...,20694,"{'currency': 'USD', 'formatted_range': '₱10K+'...",Egi finds,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",egii_tv_06,"{'amount': '22370.600599', 'currency': 'USD'}","{'amount': '22370.600599', 'currency': 'USD'}",NaN
10,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 600001]",yJHLEAAAAACOV4AEeERJl-yievH_HBss0zwVS1hGagjS2u...,0,{'formatted_range': '₱10K+'},Manh Vinh,PH,"{'age_ranges': [], 'major_gender': {'gender': ...",manh.vinh82,NaN,NaN,NaN
11,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,1102,"[601739, 600942]",-uHJVwAAAACOV4AEeERJl-yievH_HBssG-ElhJbBUq3CB3...,64221,"{'currency': 'USD', 'formatted_range': '₱10K+'...",𝙊𝙣𝙞𝙤𝙣ᥫ᭡.,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",b.rencee,"{'amount': '478175.198448', 'currency': 'USD'}","{'amount': '478126.650072', 'currency': 'USD'}",NaN
12,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,249,"[601739, 601450]",XoTXawAAAACOV4AEeERJl-yievH_HBssONvLAt04stNsY9...,38761,"{'currency': 'USD', 'formatted_range': '₱10K+'...",Kalye Guapo,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",kalyeguapo,"{'amount': '45936.92226', 'currency': 'USD'}","{'amount': '45882.099335', 'currency': 'USD'}",NaN
13,{'url': 'https://p16-common-sign.tiktokcdn.com...,17852,0,[601739],LfIZEgAAAACOV4AEeERJl-yievH_HBsscZ8ZHmnps_JQgs...,1611,{'formatted_range': '₱10K+'},vthykhanh339,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",vthykhanh339,NaN,NaN,NaN
14,{'url': 'https://p16-common-sign.tiktokcdn.com...,7678,0,[601739],cpkUwgAAAACOV4AEeERJl-yievH_HBssT5zIbCZM6VeePj...,2143,{'formatted_range': '₱10K+'},TambokTreasures,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",cellphone.shop596,NaN,NaN,NaN
15,{'url': 'https://p16-common-sign.tiktokcdn.com...,4524,0,"[601739, 604206]",MJpuawAAAACOV4AEeERJl-yievH_HBss-BKfIzRzB0IznW...,938,{'formatted_range': '₱10K+'},RizalRattan,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",gadgetdrop83,NaN,NaN,NaN
16,{'url': 'https://p16-common-sign.tiktokcdn.com...,9443,378,"[601739, 604206]",A411nwAAAACOV4AEeERJl-yievH_HBss_S4oMLwmJVXppi...,81068,"{'currency': 'USD', 'formatted_range': '₱10K+'...",Amy David,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",amydavid22,"{'amount': '44706.465138', 'currency': 'USD'}","{'amount': '4711.446301', 'currency': 'USD'}","{'amount': '39666.329679', 'currency': 'USD'}"
17,{'url': 'https://p16-common-sign.tiktokcdn.com...,17230,0,[601739],xeVgAAAAAACOV4AEeERJl-yievH_HBsswKG2Z6Z7eT5ND_...,2209,{'formatted_range': '₱10K+'},GameSexy PH,PH,"{'age_ranges': ['AGE_RANGE_55_AND_ABOVE', 'AGE...",gamesexyph,NaN,NaN,NaN
18,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,366,"[601739, 601352, 601450]",HLzZ_AAAAACOV4AEeERJl-yievH_HBssy3xbxY8iZgLcv2...,29717,"{'currency': 'USD', 'formatted_range': '₱10K+'...",Anne28,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",05garutay,"{'amount': '90659.426504', 'currency': 'USD'}","{'amount': '90645.356721', 'currency': 'USD'}",NaN
19,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 600001]",0RFWIwAAAACOV4AEeERJl-yievH_HBsstWx_jsTo2lvOIs...,4,{'formatted_range': '₱10K+'},involveasiaph02,PH,"{'age_ranges': ['AGE_RANGE_55_AND_ABOVE', 'AGE...",involveasiaph02,NaN,NaN,NaN

In [87]:
pd.DataFrame(response.json()['data']['creators'])

,avatar,avg_ec_live_uv,avg_ec_video_view_count,category_ids,creator_open_id,follower_count,gmv,gmv_range,nickname,selection_region,top_follower_demographics,username,video_gmv,live_gmv
0,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,3629,"[600001, 700437, 601739]",0Ktl2wAAAACOV4AEeERJl-yievH_HBss98ZZMcc5NxLGOJ...,127171,"{'amount': '199035.500849', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...",david sy,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",david.sy25,"{'amount': '198947.459305', 'currency': 'USD'}",NaN
1,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,1854,"[601352, 824328, 601152]",OlDpxwAAAACOV4AEeERJl-yievH_HBssyJrMiLFJf1B0bD...,26274,"{'amount': '105158.110182', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...",Fernando's Finds,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",majuuuuuuri,"{'amount': '103080.691459', 'currency': 'USD'}",NaN
2,{'url': 'https://p16-common-sign.tiktokcdn.com...,9792,39,"[601152, 605248, 824328]",vuvQSgAAAACOV4AEeERJl-yievH_HBssTBNmqgnKaxC9GP...,31628,"{'amount': '26321.024049', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...",Kikayshop.ph,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",kikayshop.ph21,"{'amount': '536.07245', 'currency': 'USD'}","{'amount': '25773.195083', 'currency': 'USD'}"
3,{'url': 'https://p19-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 600001]",9Ovn_wAAAACOV4AEeERJl-yievH_HBssS7BIL5paEZ6qYL...,531,NaN,{'formatted_range': '₱10K+'},Maria,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",user5844826884387,NaN,NaN
4,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 600001]",3MxrrwAAAACOV4AEeERJl-yievH_HBssPMIZu50b8vQOzm...,12,"{'amount': '5637882.296699', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...",iflyad03,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",iflyad03,NaN,NaN
5,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601450, 601739, 605196]",T51HRwAAAACOV4AEeERJl-yievH_HBsscpim0sGFIiscz9...,1,NaN,{'formatted_range': '₱10K+'},ShopAtHomePH,PH,"{'age_ranges': ['AGE_RANGE_35_44'], 'major_gen...",shopathomeph,NaN,NaN
6,{'url': 'https://p16-common-sign.tiktokcdn.com...,3482,645,"[601152, 824328, 603014]",rvPU_wAAAACOV4AEeERJl-yievH_HBssu77XDSFsZ1iW_V...,61375,"{'amount': '24627.49385', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...",Tita Life 🌸,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",tipid.tita,"{'amount': '12495.906165', 'currency': 'USD'}","{'amount': '12023.621935', 'currency': 'USD'}"
7,{'url': 'https://p16-common-sign.tiktokcdn.com...,6950,1464,"[601152, 605248, 601352]",3z_RngAAAACOV4AEeERJl-yievH_HBsslIUL-1c7pIG4ZK...,143433,"{'amount': '44726.476945', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...",Miss CL,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",msclstudio_3448,"{'amount': '36987.043833', 'currency': 'USD'}","{'amount': '7683.747675', 'currency': 'USD'}"
8,{'url': 'https://p16-common-sign.tiktokcdn.com...,1407,394,"[601152, 700437, 601739]",BrkGhwAAAACOV4AEeERJl-yievH_HBssTkYOrDle_jJAcY...,4430,NaN,{'formatted_range': '₱10K+'},nanaydump🥑,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",amoireelise,NaN,NaN
9,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,1882,"[601152, 600154, 824328]",yXrqVQAAAACOV4AEeERJl-yievH_HBssu5qAeG-D6YTxYx...,83879,NaN,{'formatted_range': '₱10K+'},. ݁˖ ʚjovjeanɞ . ݁˖,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",jovjean,NaN,NaN
10,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,1492,"[601152, 824328, 603014]",RvNo1QAAAACOV4AEeERJl-yievH_HBssqLttiINSdnRJgS...,238717,"{'amount': '49723.052598', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...",Deng (midsize girlie) 𐙚⋆˚✿˖°,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",qtsypie,"{'amount': '49059.348922', 'currency': 'USD'}",NaN
11,{'url': 'https://p16-common-sign.tiktokcdn.com...,6606,2928,"[601152, 601352, 605248]",67YU_gAAAACOV4AEeERJl-yievH_HBssXajjDslPKYliE3...,242197,"{'amount': '132494.683049', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...",melo,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",itsmeloaus,"{'amount': '62731.805408', 'currency': 'USD'}","{'amount': '68191.421723', 'currency': 'USD'}"
12,{'url': 'https://p16-common-sign.tiktokcdn.com...,25615,3720,"[601152, 605196, 824584]",3zhhqwAAAACOV4AEeERJl-yievH_HBss3HM6y1F1T0TTVS...,658663,NaN,{'formatted_range': '₱10K+'},Ms.Len 🥀,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",ms.len_021,NaN,NaN
13,{'url': 'https://p16-common-sign.tiktokcdn.com...,3064,439,"[601152, 824584, 600154]",A3hcnQAAAACOV4AEeERJl-yievH_HBss3jxd4XX9ccl-hS...,5090,NaN,{'formatted_range': '₱10K+'},mtrsa 𐙚༘ ⋆ ᡣ𐭩,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",mtgracious,NaN,NaN
14,{'url': 'https://p16-common-sign.tiktokcdn.com...,5543,579,"[601152, 604453, 605248]",dLd1ngAAAACOV4AEeERJl-yievH_HBss5RMTYLN7Ro9juN...,193323,"{'amount': '42875.815496', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...",Mylajoy,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",_mylajoy_,"{'amount': '1177.975602', 'currency': 'USD'}","{'amount': '41638.623246', 'currency': 'USD'}"
15,{'url': 'https://p16-common-sign.tiktokcdn.com...,6068,524,"[601152, 600001, 600024]",4rCXuwAAAACOV4AEeERJl-yievH_HBsspGt0V3VzS_b0lm...,52224,NaN,{'formatted_range': '₱10K+'},🥀,PH,"{'age_ranges': ['AGE_RANGE_35_44', 'AGE_RANGE_...",missasy6,NaN,NaN
16,{'url': 'https://p16-common-sign.tiktokcdn.com...,2729,236,"[601152, 604453, 604206]",Ho56mAAAAACOV4AEeERJl-yievH_HBssv4d1rUZkn_2HOy...,30927,NaN,{'formatted_range': '₱10K+'},𝐁𝐞𝐬𝐭 𝐂𝐡𝐨𝐢𝐜’𝐞🧿,PH,"{'age_ranges': ['AGE_RANGE_35_44', 'AGE_RANGE_...",noi.choi_o3,NaN,NaN
17,{'url': 'https://p16-common-sign.tiktokcdn.com...,655,2531,"[601152, 603014, 700645]",Z2k4tAAAAACOV4AEeERJl-yievH_HBsskT5UdWHPmT2n51...,32971,NaN,{'formatted_range': '₱10K+'},YeonaFABELLA_Hrt,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",yeonahrt,NaN,NaN
18,{'url': 'https://p16-common-sign.tiktokcdn.com...,7142,356,"[601152, 601450, 604968]",Y1ll9wAAAACOV4AEeERJl-yievH_HBss8qw530_EOotBb3...,256434,NaN,{'formatted_range': '₱10K+'},trendsbyKaila ᥫ᭡,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",trendsbykaila_,NaN,NaN
19,{'url': 'https://p16-common-sign.tiktokcdn.com...,118,1046,"[601152, 601450, 601352]",LpyDNwAAAACOV4AEeERJl-yievH_HBssv75JSbr0902BN0...,61878,"{'amount': '34962.093108', 'currency': 'USD'}","{'currency': 'USD', 'formatted_range': '₱10K+'...",Quenee.ootd,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",quin.888,"{'amount': '34899.742758', 'currency': 'USD'}",NaN

In [66]:
pd.DataFrame(response.json()['data']['creators'])

,avatar,avg_ec_live_uv,avg_ec_video_view_count,category_ids,creator_open_id,follower_count,gmv_range,nickname,selection_region,top_follower_demographics,username
0,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[601352, 601152]",I2IWFwAAAACOV4AEeERJl-yievH_HBssOVaC2_feBRCR7I...,895,{'formatted_range': '₱100-₱1K'},Jpongs_,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",jpolimar2nd
1,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[700645, 601739, 602284]",FJXiWgAAAACOV4AEeERJl-yievH_HBss6kZoZmHqG7TSuA...,1923,{'formatted_range': '₱0-₱100'},jomaryeedump,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",jomaryeedump_2000
2,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,0,"[602118, 824584, 601739]",L7PcYwAAAACOV4AEeERJl-yievH_HBsshmh4OB3xdmSeP7...,1004,{'formatted_range': '₱0-₱100'},yuni okayde😊,PH,"{'age_ranges': ['AGE_RANGE_25_34', 'AGE_RANGE_...",jomaryeedumpz
3,{'url': 'https://p16-common-sign.tiktokcdn.com...,0,2243,"[601352, 603014, 604453]",Y5EkgwAAAACOV4AEeERJl-yievH_HBssTrKMtvBlwwqFdF...,88806,{'formatted_range': '₱10K+'},Jp Olimar🇵🇭,PH,"{'age_ranges': ['AGE_RANGE_18_24'], 'major_gen...",jpongs_
4,{'url': 'https://p19-common-sign.tiktokcdn.com...,0,1385,"[600942, 801928, 602284]",OjX16gAAAACOV4AEeERJl-yievH_HBssLMogjZiSaMeXxo...,27338,{'formatted_range': '₱10K+'},Karen Anonas,PH,"{'age_ranges': ['AGE_RANGE_25_34'], 'major_gen...",karenanonas

In [58]:
response.json()

{'code': 0,
 'data': {'creators': [{'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/tos-alisg-avt-0068/c4cca57c29540180af9d3efd4fffd73f~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=fa7d2588&x-expires=1784034000&x-signature=hbyGzPtjQ4%2BeKQc5r48udYPd8%2FM%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 0,
    'avg_ec_video_view_count': 0,
    'category_ids': ['601352', '601152'],
    'creator_open_id': 'I2IWFwAAAACOV4AEeERJl-yievH_HBssOVaC2_feBRCR7IlgScbk9w',
    'follower_count': 895,
    'gmv_range': {'formatted_range': '₱100-₱1K'},
    'nickname': 'Jpongs_',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_25_34'],
     'major_gender': {'gender': 'FEMALE', 'percentage': 4217}},
    'username': 'jpolimar2nd'},
   {'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/tos-maliva-avt-0068/d75bb4500cefbbe712fe4ae267d70cef~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=6add709c&x-expires=1784034000&x-signature=1VCDlASHpZBgElq0GKD7fgHSo%2Bo%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 0,
    'avg_ec_video_view_count': 2243,
    'category_ids': ['601352', '603014', '604453'],
    'creator_open_id': 'Y5EkgwAAAACOV4AEeERJl-yievH_HBssTrKMtvBlwwqFdFUyo9iOLA',
    'follower_count': 88806,
    'gmv_range': {'formatted_range': '₱10K+'},
    'nickname': 'Jp Olimar🇵🇭',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_18_24'],
     'major_gender': {'gender': 'FEMALE', 'percentage': 6022}},
    'username': 'jpongs_'},
   {'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/tos-alisg-avt-0068/2de985c3e7b5697ddb0345f28637e390~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=4f8d6e2f&x-expires=1784034000&x-signature=UDAYk4AgxaJUFdfyI8pFdB%2B94KU%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 0,
    'avg_ec_video_view_count': 1385,
    'category_ids': ['600942', '801928', '602284'],
    'creator_open_id': 'OjX16gAAAACOV4AEeERJl-yievH_HBssLMogjZiSaMeXxo2KnUlvUw',
    'follower_count': 27338,
    'gmv_range': {'formatted_range': '₱10K+'},
    'nickname': 'Karen Anonas',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_25_34'],
     'major_gender': {'gender': 'FEMALE', 'percentage': 5473}},
    'username': 'karenanonas'},
   {'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/tos-maliva-avt-0068/d52bf49a8ab8c4e8c4124e0108985b29~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=f815df18&x-expires=1784034000&x-signature=W7Q0S65W8u9golaJcgp5%2B6D3Zto%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 0,
    'avg_ec_video_view_count': 0,
    'category_ids': ['601739', '600001', '604453'],
    'creator_open_id': 'S7jHnQAAAACOV4AEeERJl-yievH_HBsspmDYP-pIAVrUlv89kDvmzw',
    'follower_count': 31734,
    'gmv_range': {'formatted_range': '₱10K+'},
    'nickname': 'Almira Carriaga',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_25_34'],
     'major_gender': {'gender': 'FEMALE', 'percentage': 5245}},
    'username': 'almiracarriaga'},
   {'avatar': {'url': 'https://p19-common-sign.tiktokcdn.com/tos-alisg-avt-0068/5197e78a03e994587a1291fec240e500~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=5c22be2c&x-expires=1784034000&x-signature=2ht11G%2F9YrET1t%2FLlTWTQK2w3I8%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 0,
    'avg_ec_video_view_count': 0,
    'category_ids': ['601450', '601739', '600001'],
    'creator_open_id': '9Ovn_wAAAACOV4AEeERJl-yievH_HBssS7BIL5paEZ6qYLP-e3NZ_w',
    'follower_count': 531,
    'gmv_range': {'formatted_range': '₱10K+'},
    'nickname': 'Maria',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_25_34'],
     'major_gender': {'gender': 'MALE', 'percentage': 1544}},
    'username': 'user5844826884387'},
   {'avatar': {'url': 'https://p19-common-sign.tiktokcdn.com/tos-alisg-avt-0068/c118808d5a1a538204e92e528a21a97f~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=40c91cde&x-expires=1784034000&x-signature=dmr73r4GF%2F2v0B0tEkOsCPhltLc%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 0,
    'avg_ec_video_view_count': 0,
    'category_ids': ['601450', '601739', '600001'],
    'creator_open_id': '3MxrrwAAAACOV4AEeERJl-yievH_HBssPMIZu50b8vQOzmFDSvHglQ',
    'follower_count': 12,
    'gmv': {'amount': '5637882.296699', 'currency': 'USD'},
    'gmv_range': {'currency': 'USD',
     'formatted_range': '₱10K+',
     'minimum_amount': '10000'},
    'nickname': 'iflyad03',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_25_34'],
     'major_gender': {'gender': 'FEMALE', 'percentage': 4615}},
    'username': 'iflyad03'},
   {'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/musically-maliva-obj/1594805258216454~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=7a36ca17&x-expires=1784034000&x-signature=TjzZl%2BjVXBg1T2mwpTohEE6AGms%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 0,
    'avg_ec_video_view_count': 0,
    'category_ids': ['601450', '601739', '605196'],
    'creator_open_id': 'T51HRwAAAACOV4AEeERJl-yievH_HBsscpim0sGFIiscz9pYkPWviA',
    'follower_count': 1,
    'gmv_range': {'formatted_range': '₱10K+'},
    'nickname': 'ShopAtHomePH',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_35_44'],
     'major_gender': {'gender': 'MALE', 'percentage': 10000}},
    'username': 'shopathomeph'},
   {'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/tos-alisg-avt-0068/ac781366a3aac83d1bda494842e06b6a~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=2179569d&x-expires=1784034000&x-signature=VtxWO95P8HryYiPowZn2vIsKuTI%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 0,
    'avg_ec_video_view_count': 0,
    'category_ids': ['601739', '605196', '601450'],
    'creator_open_id': 'Bk01NQAAAACOV4AEeERJl-yievH_HBssjYBT2NCiw6gm5afPaGEhEg',
    'follower_count': 787,
    'gmv': {'amount': '28293.612369', 'currency': 'USD'},
    'gmv_range': {'currency': 'USD',
     'formatted_range': '₱10K+',
     'minimum_amount': '10000'},
    'nickname': 'Nicolas Pagquil',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_25_34'],
     'major_gender': {'gender': 'FEMALE', 'percentage': 4585}},
    'username': 'nicolas.pagquil'},
   {'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/tos-alisg-avt-0068/ceea8430c4ad52180cad2aea565ac02a~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=10126c44&x-expires=1784034000&x-signature=%2FJAbuDEuRaBgrO0BuT1Vb3ng3Wk%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=a1d2006b&idc=my2'},
    'avg_ec_live_uv': 102597,
    'avg_ec_video_view_count': 0,
    'category_ids': ['601739', '601755'],
    'creator_open_id': 'jSATJgAAAACOV4AEeERJl-yievH_HBssugnh2geIdZYbIX71FCECKg',
    'follower_count': 114602,
    'gmv_range': {'formatted_range': '₱10K+'},
    'nickname': 'Hari ng Chamba',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_25_34',
      'AGE_RANGE_18_24'],
     'major_gender': {'gender': 'FEMALE', 'percentage': 1891}},
    'username': 'haringchamba'},
   {'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/tos-alisg-avt-0068/343b605880861266445129318af57fce~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=b054ce2c&x-expires=1784034000&x-signature=JKjDCY8gVa5%2BMFMWPjkVC2jlEUA%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 0,
    'avg_ec_video_view_count': 263,
    'category_ids': ['601739', '604968', '605196'],
    'creator_open_id': '4WFi3gAAAACOV4AEeERJl-yievH_HBss5966XF9PQoqdpSJby4p-KQ',
    'follower_count': 20694,
    'gmv': {'amount': '22370.600599', 'currency': 'USD'},
    'gmv_range': {'currency': 'USD',
     'formatted_range': '₱10K+',
     'minimum_amount': '10000'},
    'nickname': 'Egi finds',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_25_34'],
     'major_gender': {'gender': 'MALE', 'percentage': 6016}},
    'username': 'egii_tv_06',
    'video_gmv': {'amount': '22370.600599', 'currency': 'USD'}},
   {'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/tos-alisg-avt-0068/3d584b361335bcd88931a0444da6a352~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=675c3f2b&x-expires=1784034000&x-signature=PYANJpKnYFmyWWfH5orCY7KsjxQ%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 0,
    'avg_ec_video_view_count': 0,
    'category_ids': ['601450', '601739', '600001'],
    'creator_open_id': 'yJHLEAAAAACOV4AEeERJl-yievH_HBss0zwVS1hGagjS2uJ9eOf8Zw',
    'follower_count': 0,
    'gmv_range': {'formatted_range': '₱10K+'},
    'nickname': 'Manh Vinh',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': [],
     'major_gender': {'gender': 'FEMALE', 'percentage': 0}},
    'username': 'manh.vinh82'},
   {'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/tos-alisg-avt-0068/f250efa7a4939f9568865bde14c7a080~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=4c88b152&x-expires=1784034000&x-signature=z0CHTBmfBSEd5Umb45iQSPAQPys%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 0,
    'avg_ec_video_view_count': 1102,
    'category_ids': ['601739', '600942'],
    'creator_open_id': '-uHJVwAAAACOV4AEeERJl-yievH_HBssG-ElhJbBUq3CB3P4KRQhSg',
    'follower_count': 64221,
    'gmv': {'amount': '478175.198448', 'currency': 'USD'},
    'gmv_range': {'currency': 'USD',
     'formatted_range': '₱10K+',
     'minimum_amount': '10000'},
    'nickname': '𝙊𝙣𝙞𝙤𝙣ᥫ᭡.',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_25_34',
      'AGE_RANGE_35_44'],
     'major_gender': {'gender': 'FEMALE', 'percentage': 1827}},
    'username': 'b.rencee',
    'video_gmv': {'amount': '478126.650072', 'currency': 'USD'}},
   {'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/tos-alisg-avt-0068/df8fb02eb972d3521427b1c15dcf8a0b~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=ac80fbb5&x-expires=1784034000&x-signature=Zp%2BGOz0EAeDVK%2F9e%2BOM0LwjbQlg%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 0,
    'avg_ec_video_view_count': 249,
    'category_ids': ['601739', '601450'],
    'creator_open_id': 'XoTXawAAAACOV4AEeERJl-yievH_HBssONvLAt04stNsY96fQBjXxA',
    'follower_count': 38761,
    'gmv': {'amount': '45936.92226', 'currency': 'USD'},
    'gmv_range': {'currency': 'USD',
     'formatted_range': '₱10K+',
     'minimum_amount': '10000'},
    'nickname': 'Kalye Guapo',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_25_34'],
     'major_gender': {'gender': 'MALE', 'percentage': 4617}},
    'username': 'kalyeguapo',
    'video_gmv': {'amount': '45882.099335', 'currency': 'USD'}},
   {'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/tos-alisg-avt-0068/786928e45d053ee04d061fdb2b3f51fd~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=eb1a806c&x-expires=1784034000&x-signature=5U36DB3UdqbTQpDbEFffEw4bLa4%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 17852,
    'avg_ec_video_view_count': 0,
    'category_ids': ['601739'],
    'creator_open_id': 'LfIZEgAAAACOV4AEeERJl-yievH_HBsscZ8ZHmnps_JQgsU1t01VrQ',
    'follower_count': 1611,
    'gmv_range': {'formatted_range': '₱10K+'},
    'nickname': 'vthykhanh339',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_25_34',
      'AGE_RANGE_35_44'],
     'major_gender': {'gender': 'FEMALE', 'percentage': 3405}},
    'username': 'vthykhanh339'},
   {'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/tos-alisg-avt-0068/c02c87630cef5aee873da1bd11add5db~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=c1ba76d8&x-expires=1784034000&x-signature=H7QeXNOyrrsDccte1sA8oV6o4PM%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 7678,
    'avg_ec_video_view_count': 0,
    'category_ids': ['601739'],
    'creator_open_id': 'cpkUwgAAAACOV4AEeERJl-yievH_HBssT5zIbCZM6VeePjYY2FPgqA',
    'follower_count': 2143,
    'gmv_range': {'formatted_range': '₱10K+'},
    'nickname': 'TambokTreasures',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_25_34',
      'AGE_RANGE_35_44'],
     'major_gender': {'gender': 'FEMALE', 'percentage': 3361}},
    'username': 'cellphone.shop596'},
   {'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/tos-alisg-avt-0068/94f3e619a00688bde7ae30b0745119a0~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=a1e70c71&x-expires=1784034000&x-signature=48jGlo%2BwMl5TBVK8Ah10RPBK5rs%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 4524,
    'avg_ec_video_view_count': 0,
    'category_ids': ['601739', '604206'],
    'creator_open_id': 'MJpuawAAAACOV4AEeERJl-yievH_HBss-BKfIzRzB0IznWorLCgEiQ',
    'follower_count': 938,
    'gmv_range': {'formatted_range': '₱10K+'},
    'nickname': 'RizalRattan',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_25_34',
      'AGE_RANGE_35_44'],
     'major_gender': {'gender': 'FEMALE', 'percentage': 3049}},
    'username': 'gadgetdrop83'},
   {'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/tos-alisg-avt-0068/a2fdd8b65db96e3171283085a298670f~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=392581fa&x-expires=1784034000&x-signature=zYPCCGzjjDiDUt9FI79A8dFD4KY%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 9443,
    'avg_ec_video_view_count': 378,
    'category_ids': ['601739', '604206'],
    'creator_open_id': 'A411nwAAAACOV4AEeERJl-yievH_HBss_S4oMLwmJVXppiZPcp5jXQ',
    'follower_count': 81068,
    'gmv': {'amount': '44706.465138', 'currency': 'USD'},
    'gmv_range': {'currency': 'USD',
     'formatted_range': '₱10K+',
     'minimum_amount': '10000'},
    'live_gmv': {'amount': '39666.329679', 'currency': 'USD'},
    'nickname': 'Amy David',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_25_34',
      'AGE_RANGE_18_24'],
     'major_gender': {'gender': 'FEMALE', 'percentage': 4727}},
    'username': 'amydavid22',
    'video_gmv': {'amount': '4711.446301', 'currency': 'USD'}},
   {'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/tos-alisg-avt-0068/f67ce18907ee083a5a25a53ae7fe7783~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=553acb2f&x-expires=1784034000&x-signature=%2FkeLh4HfS3ZwMiZ%2B1RTvvtImo94%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 17230,
    'avg_ec_video_view_count': 0,
    'category_ids': ['601739'],
    'creator_open_id': 'xeVgAAAAAACOV4AEeERJl-yievH_HBsswKG2Z6Z7eT5ND_bfT5nvwQ',
    'follower_count': 2209,
    'gmv_range': {'formatted_range': '₱10K+'},
    'nickname': 'GameSexy PH',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_55_AND_ABOVE',
      'AGE_RANGE_25_34'],
     'major_gender': {'gender': 'FEMALE', 'percentage': 2604}},
    'username': 'gamesexyph'},
   {'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/tos-alisg-avt-0068/b96e7612316ed203073dfedd3ab54502~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=04a46cee&x-expires=1784034000&x-signature=LEeh1mEi1ORbW540Mo2DM08ecow%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 0,
    'avg_ec_video_view_count': 366,
    'category_ids': ['601739', '601352', '601450'],
    'creator_open_id': 'HLzZ_AAAAACOV4AEeERJl-yievH_HBssy3xbxY8iZgLcv2LW-DBiDw',
    'follower_count': 29717,
    'gmv': {'amount': '90659.426504', 'currency': 'USD'},
    'gmv_range': {'currency': 'USD',
     'formatted_range': '₱10K+',
     'minimum_amount': '10000'},
    'nickname': 'Anne28',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_25_34'],
     'major_gender': {'gender': 'FEMALE', 'percentage': 3495}},
    'username': '05garutay',
    'video_gmv': {'amount': '90645.356721', 'currency': 'USD'}},
   {'avatar': {'url': 'https://p16-common-sign.tiktokcdn.com/musically-maliva-obj/1594805258216454~tplv-tiktokx-cropcenter:720:720.webp?dr=14579&refresh_token=7a36ca17&x-expires=1784034000&x-signature=TjzZl%2BjVXBg1T2mwpTohEE6AGms%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=39dffb78&idc=my2'},
    'avg_ec_live_uv': 0,
    'avg_ec_video_view_count': 0,
    'category_ids': ['601450', '601739', '600001'],
    'creator_open_id': '0RFWIwAAAACOV4AEeERJl-yievH_HBsstWx_jsTo2lvOIsfYvT0mNQ',
    'follower_count': 4,
    'gmv_range': {'formatted_range': '₱10K+'},
    'nickname': 'involveasiaph02',
    'selection_region': 'PH',
    'top_follower_demographics': {'age_ranges': ['AGE_RANGE_55_AND_ABOVE',
      'AGE_RANGE_35_44',
      'AGE_RANGE_25_34'],
     'major_gender': {'gender': 'MALE', 'percentage': 5000}},
    'username': 'involveasiaph02'}],
  'next_page_token': 'b2Zmc2V0PTIw',
  'search_key': 'hyPwMBTvMVhNPXbpSseLSaXiHQ1oWMEtK59WmABBFsU='},
 'message': 'Success',
 'request_id': '2026071221451007BA74447108DA82D7FE'}